nn_cfg:
  lr: 1e-2
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 1000
  epochs: 100

data:
  datetime: ''

eval_every_x_epochs: 2
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 10

N_train: 10000
N_test: 10
num_samples: 10


plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'


accuracies: [.1, .01, .001, .0001]

skip_startup: False

eval_unrolls: 1000
supervised: True
train_unrolls: 10

# load_weights_datetime: '2023-08-28/16-14-46'
# nn_load_type: deterministic
# load_weights_datetime: '2024-01-07/13-07-24'
# nn_load_type: stochastic
# save_weights_flag: True

pac_bayes_cfg:
  init_var: 1e-3
  c: 10.0
  b: 100
  delta: 0.0001
  rep: True
  penalty_coeff: 1.0
  deterministic: False
  target_pen: 0.3
  frac_solved_accs: [0.1, 0.01]

algo: 'l2ws'