model: lasco
nn_cfg:
  lr: 1e-1
  method: adam
  batch_size: 1000
  epochs: 200


data:
  datetime: ''

train_unrolls: 10
eval_unrolls: 200
eval_every_x_epochs: 200
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 2
N_train: 10
N_test: 1000
N_val: 1000
# num_samples: 10
num_samples_train: 1000
num_samples_test: 1000
supervised: True
plot_iterates: [0, 10, 900]
loss_method: 'fixed_k'
accuracies: [.1, .01, .001, .0001]